### ISSUE TITLE
Asset folder not supported for CMS 16

### ISSUE THREAD

**Issue by FiXerCz** [erminas/smartapi#6]
Hello,
processing project folders on CMS 16.0 throws exception, when folders contain folder type "Asset" (introduced in the version 16). Looks like "Asset" folder type is not yet supported by SmartApi.

Are you planning to add this functionality?

**Here is the exception:**

erminas.SmartAPI.Exceptions.SmartAPIException: Could not convert value '2' of attribute 'catalog' to a boolean value
   at erminas.SmartAPI.Utils.XmlUtil.GetBoolAttributeValue(XmlElement xmlElement, String attributeName)
   at erminas.SmartAPI.CMS.Project.Folder.InternalFolderFactory.CreateFolder(IProject project, XmlElement element)
   at erminas.SmartAPI.CMS.Project.Folders.<GetFolders>b__13_1(XmlElement curNode)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at erminas.SmartAPI.CMS.Project.Folders.GetFolders()
   at erminas.SmartAPI.Utils.CachedCollections.CachedList`1.EnsureListIsLoaded()
   at erminas.SmartAPI.Utils.CachedCollections.CachedList`1.GetEnumerator()
   .....

The exception can be replicated by simly iterating over the projects folders for a project, that contains folder of type "Asset".

**Comment by jjacobi** [comment]
The current develop branch of the smartapi supports Asset folder types.
We'll probably have a new stable release in the not so distant future containing it.
